---

ntp:
  servers:
  - ip: 192.168.18.148

bgp:
  id: '65001'
  rid: 1.1.1.2
  neighbors:
  - id: 1.1.1.1
    as: '65001'
    loopsource: '0'
  - id: 1.1.1.3
    as: '65001'
    loopsource: '0'
  - id: 1.1.1.4
    as: '65001'
    loopsource: '0'
  ipv4_unicast_family:
  - neighborid: 1.1.1.1
  - neighborid: 1.1.1.3
  - neighborid: 1.1.1.4
  networks:
  - number: 20.20.20.0
    mask: 255.255.255.0
  - number: 25.25.25.0
    mask: 255.255.255.0


ospf:
  id: '1'
  rid: 1.1.1.2
  networks:
  - ip: 1.1.1.2
    mask: 0.0.0.0
    area: '0'
  - ip: 172.168.200.0
    mask: 0.0.0.255
    area: '0'

ip:
  domain: cisco.com
  tftp_source_gi_int: '1'
  source_interface: GigabitEthernet1
  vrf:
  - name: MGMT
    description: OOB Management
  extended_acl:
  - name: '111'
    sequences:
    - number: '10'
      action: permit
      protocol: ip
      srcip: 172.168.200.0
      srcmask: 0.0.0.255
      destip: 172.168.100.0
      destmask: 0.0.0.255

