---

inventory:
    plugin: SimpleInventory
    options:
        host_file: "/home/imad/Nornir-Automation/hosts.yaml"
        group_file: "/home/imad/Nornir-Automation/groups.yaml"
        defaults_file: "/home/imad/Nornir-Automation/defaults.yaml"

runner:
    plugin: threaded
    options:
        num_workers: 10